
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BlogServicioImplService", targetNamespace = "http://servicio/", wsdlLocation = "http://localhost:8080/BlogServicioImplService/BlogServicioImpl?wsdl")
public class BlogServicioImplService
    extends Service
{

    private final static URL BLOGSERVICIOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BLOGSERVICIOIMPLSERVICE_EXCEPTION;
    private final static QName BLOGSERVICIOIMPLSERVICE_QNAME = new QName("http://servicio/", "BlogServicioImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BlogServicioImplService/BlogServicioImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BLOGSERVICIOIMPLSERVICE_WSDL_LOCATION = url;
        BLOGSERVICIOIMPLSERVICE_EXCEPTION = e;
    }

    public BlogServicioImplService() {
        super(__getWsdlLocation(), BLOGSERVICIOIMPLSERVICE_QNAME);
    }

    public BlogServicioImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BLOGSERVICIOIMPLSERVICE_QNAME, features);
    }

    public BlogServicioImplService(URL wsdlLocation) {
        super(wsdlLocation, BLOGSERVICIOIMPLSERVICE_QNAME);
    }

    public BlogServicioImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BLOGSERVICIOIMPLSERVICE_QNAME, features);
    }

    public BlogServicioImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BlogServicioImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BlogServicioWS
     */
    @WebEndpoint(name = "BlogServicioImplPort")
    public BlogServicioWS getBlogServicioImplPort() {
        return super.getPort(new QName("http://servicio/", "BlogServicioImplPort"), BlogServicioWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BlogServicioWS
     */
    @WebEndpoint(name = "BlogServicioImplPort")
    public BlogServicioWS getBlogServicioImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio/", "BlogServicioImplPort"), BlogServicioWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BLOGSERVICIOIMPLSERVICE_EXCEPTION!= null) {
            throw BLOGSERVICIOIMPLSERVICE_EXCEPTION;
        }
        return BLOGSERVICIOIMPLSERVICE_WSDL_LOCATION;
    }

}
