
package webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BlogServicioWS", targetNamespace = "http://servicio/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BlogServicioWS {


    /**
     * 
     * @return
     *     returns java.util.List<webservice.Blogs>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarTodosLosBlogs", targetNamespace = "http://servicio/", className = "webservice.BuscarTodosLosBlogs")
    @ResponseWrapper(localName = "buscarTodosLosBlogsResponse", targetNamespace = "http://servicio/", className = "webservice.BuscarTodosLosBlogsResponse")
    @Action(input = "http://servicio/BlogServicioWS/buscarTodosLosBlogsRequest", output = "http://servicio/BlogServicioWS/buscarTodosLosBlogsResponse")
    public List<Blogs> buscarTodosLosBlogs();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.Blogs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarBlogPorId", targetNamespace = "http://servicio/", className = "webservice.BuscarBlogPorId")
    @ResponseWrapper(localName = "buscarBlogPorIdResponse", targetNamespace = "http://servicio/", className = "webservice.BuscarBlogPorIdResponse")
    @Action(input = "http://servicio/BlogServicioWS/buscarBlogPorIdRequest", output = "http://servicio/BlogServicioWS/buscarBlogPorIdResponse")
    public Blogs buscarBlogPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Blogs arg0);

}
